version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    networks:
      - wine_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
      - mysql
    container_name: wine-sommelier-app
    image: nazar5n/virtual-wine-sommelier:1.0.0
    restart: on-failure
    build: .
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQLDB_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - wine_network
    volumes:
      - ./target:/app/target
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${APP_DOCKER_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wine_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
